/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoetzRouteImport } from './routes/yoetz'
import { Route as TichnunPiansiRouteImport } from './routes/tichnun-piansi'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TaoyotRouteImport } from './routes/taoyot'
import { Route as StartRouteImport } from './routes/start'
import { Route as ShukHahonRouteImport } from './routes/shuk-hahon'
import { Route as ShkifutRouteImport } from './routes/shkifut'
import { Route as ShitufimRouteImport } from './routes/shitufim'
import { Route as NadlanRouteImport } from './routes/nadlan'
import { Route as MashkantaotRouteImport } from './routes/mashkantaot'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaoyotSlugRouteImport } from './routes/taoyot.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalDisclosureRouteImport } from './routes/legal/disclosure'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalAccessibilityRouteImport } from './routes/legal/accessibility'
import { Route as CalculatorsRealestateRouteImport } from './routes/calculators/realestate'
import { Route as CalculatorsPensionRouteImport } from './routes/calculators/pension'
import { Route as CalculatorsMortgageRouteImport } from './routes/calculators/mortgage'
import { Route as CalculatorsInvestRouteImport } from './routes/calculators/invest'
import { Route as CalculatorsFamilyRouteImport } from './routes/calculators/family'
import { Route as CalculatorsCompoundRouteImport } from './routes/calculators/compound'
import { Route as CalculatorsChildRouteImport } from './routes/calculators/child'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const YoetzRoute = YoetzRouteImport.update({
  id: '/yoetz',
  path: '/yoetz',
  getParentRoute: () => rootRouteImport,
} as any)
const TichnunPiansiRoute = TichnunPiansiRouteImport.update({
  id: '/tichnun-piansi',
  path: '/tichnun-piansi',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TaoyotRoute = TaoyotRouteImport.update({
  id: '/taoyot',
  path: '/taoyot',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ShukHahonRoute = ShukHahonRouteImport.update({
  id: '/shuk-hahon',
  path: '/shuk-hahon',
  getParentRoute: () => rootRouteImport,
} as any)
const ShkifutRoute = ShkifutRouteImport.update({
  id: '/shkifut',
  path: '/shkifut',
  getParentRoute: () => rootRouteImport,
} as any)
const ShitufimRoute = ShitufimRouteImport.update({
  id: '/shitufim',
  path: '/shitufim',
  getParentRoute: () => rootRouteImport,
} as any)
const NadlanRoute = NadlanRouteImport.update({
  id: '/nadlan',
  path: '/nadlan',
  getParentRoute: () => rootRouteImport,
} as any)
const MashkantaotRoute = MashkantaotRouteImport.update({
  id: '/mashkantaot',
  path: '/mashkantaot',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaoyotSlugRoute = TaoyotSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TaoyotRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclosureRoute = LegalDisclosureRouteImport.update({
  id: '/legal/disclosure',
  path: '/legal/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAccessibilityRoute = LegalAccessibilityRouteImport.update({
  id: '/legal/accessibility',
  path: '/legal/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRealestateRoute = CalculatorsRealestateRouteImport.update({
  id: '/realestate',
  path: '/realestate',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsPensionRoute = CalculatorsPensionRouteImport.update({
  id: '/pension',
  path: '/pension',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsMortgageRoute = CalculatorsMortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsInvestRoute = CalculatorsInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsFamilyRoute = CalculatorsFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsCompoundRoute = CalculatorsCompoundRouteImport.update({
  id: '/compound',
  path: '/compound',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsChildRoute = CalculatorsChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => CalculatorsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculators': typeof CalculatorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/mashkantaot': typeof MashkantaotRoute
  '/nadlan': typeof NadlanRoute
  '/shitufim': typeof ShitufimRoute
  '/shkifut': typeof ShkifutRoute
  '/shuk-hahon': typeof ShukHahonRoute
  '/start': typeof StartRoute
  '/taoyot': typeof TaoyotRouteWithChildren
  '/thank-you': typeof ThankYouRoute
  '/tichnun-piansi': typeof TichnunPiansiRoute
  '/yoetz': typeof YoetzRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculators/child': typeof CalculatorsChildRoute
  '/calculators/compound': typeof CalculatorsCompoundRoute
  '/calculators/family': typeof CalculatorsFamilyRoute
  '/calculators/invest': typeof CalculatorsInvestRoute
  '/calculators/mortgage': typeof CalculatorsMortgageRoute
  '/calculators/pension': typeof CalculatorsPensionRoute
  '/calculators/realestate': typeof CalculatorsRealestateRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclosure': typeof LegalDisclosureRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/taoyot/$slug': typeof TaoyotSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculators': typeof CalculatorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/mashkantaot': typeof MashkantaotRoute
  '/nadlan': typeof NadlanRoute
  '/shitufim': typeof ShitufimRoute
  '/shkifut': typeof ShkifutRoute
  '/shuk-hahon': typeof ShukHahonRoute
  '/start': typeof StartRoute
  '/taoyot': typeof TaoyotRouteWithChildren
  '/thank-you': typeof ThankYouRoute
  '/tichnun-piansi': typeof TichnunPiansiRoute
  '/yoetz': typeof YoetzRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculators/child': typeof CalculatorsChildRoute
  '/calculators/compound': typeof CalculatorsCompoundRoute
  '/calculators/family': typeof CalculatorsFamilyRoute
  '/calculators/invest': typeof CalculatorsInvestRoute
  '/calculators/mortgage': typeof CalculatorsMortgageRoute
  '/calculators/pension': typeof CalculatorsPensionRoute
  '/calculators/realestate': typeof CalculatorsRealestateRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclosure': typeof LegalDisclosureRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/taoyot/$slug': typeof TaoyotSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculators': typeof CalculatorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/mashkantaot': typeof MashkantaotRoute
  '/nadlan': typeof NadlanRoute
  '/shitufim': typeof ShitufimRoute
  '/shkifut': typeof ShkifutRoute
  '/shuk-hahon': typeof ShukHahonRoute
  '/start': typeof StartRoute
  '/taoyot': typeof TaoyotRouteWithChildren
  '/thank-you': typeof ThankYouRoute
  '/tichnun-piansi': typeof TichnunPiansiRoute
  '/yoetz': typeof YoetzRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculators/child': typeof CalculatorsChildRoute
  '/calculators/compound': typeof CalculatorsCompoundRoute
  '/calculators/family': typeof CalculatorsFamilyRoute
  '/calculators/invest': typeof CalculatorsInvestRoute
  '/calculators/mortgage': typeof CalculatorsMortgageRoute
  '/calculators/pension': typeof CalculatorsPensionRoute
  '/calculators/realestate': typeof CalculatorsRealestateRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclosure': typeof LegalDisclosureRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/taoyot/$slug': typeof TaoyotSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/calculators'
    | '/contact'
    | '/mashkantaot'
    | '/nadlan'
    | '/shitufim'
    | '/shkifut'
    | '/shuk-hahon'
    | '/start'
    | '/taoyot'
    | '/thank-you'
    | '/tichnun-piansi'
    | '/yoetz'
    | '/blog/$slug'
    | '/calculators/child'
    | '/calculators/compound'
    | '/calculators/family'
    | '/calculators/invest'
    | '/calculators/mortgage'
    | '/calculators/pension'
    | '/calculators/realestate'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/disclosure'
    | '/legal/privacy'
    | '/legal/terms'
    | '/taoyot/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/calculators'
    | '/contact'
    | '/mashkantaot'
    | '/nadlan'
    | '/shitufim'
    | '/shkifut'
    | '/shuk-hahon'
    | '/start'
    | '/taoyot'
    | '/thank-you'
    | '/tichnun-piansi'
    | '/yoetz'
    | '/blog/$slug'
    | '/calculators/child'
    | '/calculators/compound'
    | '/calculators/family'
    | '/calculators/invest'
    | '/calculators/mortgage'
    | '/calculators/pension'
    | '/calculators/realestate'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/disclosure'
    | '/legal/privacy'
    | '/legal/terms'
    | '/taoyot/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/calculators'
    | '/contact'
    | '/mashkantaot'
    | '/nadlan'
    | '/shitufim'
    | '/shkifut'
    | '/shuk-hahon'
    | '/start'
    | '/taoyot'
    | '/thank-you'
    | '/tichnun-piansi'
    | '/yoetz'
    | '/blog/$slug'
    | '/calculators/child'
    | '/calculators/compound'
    | '/calculators/family'
    | '/calculators/invest'
    | '/calculators/mortgage'
    | '/calculators/pension'
    | '/calculators/realestate'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/disclosure'
    | '/legal/privacy'
    | '/legal/terms'
    | '/taoyot/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculatorsRoute: typeof CalculatorsRouteWithChildren
  ContactRoute: typeof ContactRoute
  MashkantaotRoute: typeof MashkantaotRoute
  NadlanRoute: typeof NadlanRoute
  ShitufimRoute: typeof ShitufimRoute
  ShkifutRoute: typeof ShkifutRoute
  ShukHahonRoute: typeof ShukHahonRoute
  StartRoute: typeof StartRoute
  TaoyotRoute: typeof TaoyotRouteWithChildren
  ThankYouRoute: typeof ThankYouRoute
  TichnunPiansiRoute: typeof TichnunPiansiRoute
  YoetzRoute: typeof YoetzRoute
  LegalAccessibilityRoute: typeof LegalAccessibilityRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDisclosureRoute: typeof LegalDisclosureRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoetz': {
      id: '/yoetz'
      path: '/yoetz'
      fullPath: '/yoetz'
      preLoaderRoute: typeof YoetzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tichnun-piansi': {
      id: '/tichnun-piansi'
      path: '/tichnun-piansi'
      fullPath: '/tichnun-piansi'
      preLoaderRoute: typeof TichnunPiansiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taoyot': {
      id: '/taoyot'
      path: '/taoyot'
      fullPath: '/taoyot'
      preLoaderRoute: typeof TaoyotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuk-hahon': {
      id: '/shuk-hahon'
      path: '/shuk-hahon'
      fullPath: '/shuk-hahon'
      preLoaderRoute: typeof ShukHahonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shkifut': {
      id: '/shkifut'
      path: '/shkifut'
      fullPath: '/shkifut'
      preLoaderRoute: typeof ShkifutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shitufim': {
      id: '/shitufim'
      path: '/shitufim'
      fullPath: '/shitufim'
      preLoaderRoute: typeof ShitufimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nadlan': {
      id: '/nadlan'
      path: '/nadlan'
      fullPath: '/nadlan'
      preLoaderRoute: typeof NadlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mashkantaot': {
      id: '/mashkantaot'
      path: '/mashkantaot'
      fullPath: '/mashkantaot'
      preLoaderRoute: typeof MashkantaotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taoyot/$slug': {
      id: '/taoyot/$slug'
      path: '/$slug'
      fullPath: '/taoyot/$slug'
      preLoaderRoute: typeof TaoyotSlugRouteImport
      parentRoute: typeof TaoyotRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclosure': {
      id: '/legal/disclosure'
      path: '/legal/disclosure'
      fullPath: '/legal/disclosure'
      preLoaderRoute: typeof LegalDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/legal/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof LegalAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/realestate': {
      id: '/calculators/realestate'
      path: '/realestate'
      fullPath: '/calculators/realestate'
      preLoaderRoute: typeof CalculatorsRealestateRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/pension': {
      id: '/calculators/pension'
      path: '/pension'
      fullPath: '/calculators/pension'
      preLoaderRoute: typeof CalculatorsPensionRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/mortgage': {
      id: '/calculators/mortgage'
      path: '/mortgage'
      fullPath: '/calculators/mortgage'
      preLoaderRoute: typeof CalculatorsMortgageRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/invest': {
      id: '/calculators/invest'
      path: '/invest'
      fullPath: '/calculators/invest'
      preLoaderRoute: typeof CalculatorsInvestRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/family': {
      id: '/calculators/family'
      path: '/family'
      fullPath: '/calculators/family'
      preLoaderRoute: typeof CalculatorsFamilyRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/compound': {
      id: '/calculators/compound'
      path: '/compound'
      fullPath: '/calculators/compound'
      preLoaderRoute: typeof CalculatorsCompoundRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/child': {
      id: '/calculators/child'
      path: '/child'
      fullPath: '/calculators/child'
      preLoaderRoute: typeof CalculatorsChildRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CalculatorsRouteChildren {
  CalculatorsChildRoute: typeof CalculatorsChildRoute
  CalculatorsCompoundRoute: typeof CalculatorsCompoundRoute
  CalculatorsFamilyRoute: typeof CalculatorsFamilyRoute
  CalculatorsInvestRoute: typeof CalculatorsInvestRoute
  CalculatorsMortgageRoute: typeof CalculatorsMortgageRoute
  CalculatorsPensionRoute: typeof CalculatorsPensionRoute
  CalculatorsRealestateRoute: typeof CalculatorsRealestateRoute
}

const CalculatorsRouteChildren: CalculatorsRouteChildren = {
  CalculatorsChildRoute: CalculatorsChildRoute,
  CalculatorsCompoundRoute: CalculatorsCompoundRoute,
  CalculatorsFamilyRoute: CalculatorsFamilyRoute,
  CalculatorsInvestRoute: CalculatorsInvestRoute,
  CalculatorsMortgageRoute: CalculatorsMortgageRoute,
  CalculatorsPensionRoute: CalculatorsPensionRoute,
  CalculatorsRealestateRoute: CalculatorsRealestateRoute,
}

const CalculatorsRouteWithChildren = CalculatorsRoute._addFileChildren(
  CalculatorsRouteChildren,
)

interface TaoyotRouteChildren {
  TaoyotSlugRoute: typeof TaoyotSlugRoute
}

const TaoyotRouteChildren: TaoyotRouteChildren = {
  TaoyotSlugRoute: TaoyotSlugRoute,
}

const TaoyotRouteWithChildren =
  TaoyotRoute._addFileChildren(TaoyotRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculatorsRoute: CalculatorsRouteWithChildren,
  ContactRoute: ContactRoute,
  MashkantaotRoute: MashkantaotRoute,
  NadlanRoute: NadlanRoute,
  ShitufimRoute: ShitufimRoute,
  ShkifutRoute: ShkifutRoute,
  ShukHahonRoute: ShukHahonRoute,
  StartRoute: StartRoute,
  TaoyotRoute: TaoyotRouteWithChildren,
  ThankYouRoute: ThankYouRoute,
  TichnunPiansiRoute: TichnunPiansiRoute,
  YoetzRoute: YoetzRoute,
  LegalAccessibilityRoute: LegalAccessibilityRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDisclosureRoute: LegalDisclosureRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
